import { sign } from 'crypto';
import { type NextPage } from 'next';
import { signIn, signOut, useSession } from 'next-auth/react';
import Head from 'next/head';
import Link from 'next/link';

import { api } from '~/utils/api';

const Home: NextPage = () => {
  const { data } = api.example.hello.useQuery({ text: 'from tRPC' });
  const { data: sessionData } = useSession();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-3">
        {!sessionData && (
          <button onClick={() => signIn()} className="btn">
            Sign-in
          </button>
        )}
        {sessionData && (
          <button onClick={() => signOut()} className="btn">
            Sign-out
          </button>
        )}
        <p>{sessionData?.user.email}</p>
        <p>{data?.greeting}</p>
      </main>
    </>
  );
};

export default Home;
